apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gpo4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0010-tenant/tkrw-pr712-0075-0010-app/devfile-sample-gpo4@sha256:935f3e80c2b057f3e4aa51e78ab2b0f8df3326bf96487567b60cfda730cb2c88
        name: my-nodejs
        resources: {}
status: {}
